template: |
  ## Changes
  $CHANGES

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-template: "$MAJOR.$MINOR.$PATCH"
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-title-escapes: '\<*_&'

categories:
  - title: "ðŸš€ New Features"
    labels:
      - "type:feature"
      - "type:style"
      - "type:test"
  - title: "ðŸž Bugs Fixes"
    labels:
      - "type:bugfix"
  - title: "ðŸ“š Documentation"
    labels:
      - "type:docs"
  - title: "ðŸ§° Maintenance"
    labels:
      - "type:refactor"
      - "type:perf"
  - title: "ðŸ›  Configuration"
    labels:
      - "type:config"
      - "type:build"
      - "type:ci"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "type:feature"
      - "type:style"
      - "type:docs"
      - "type:perf"
  patch:
    labels:
      - "patch"
      - "type:bugfix"
      - "type:build"
      - "type:ci"
      - "type:refactor"
      - "type:test"
      - "type:config"
  default: patch
