name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "🚀 New Features"
    labels:
      - "type:feature"
  - title: "🐞 Bugs Fixes"
    labels:
      - "type:bugfix"
  - title: "📚 Documentation"
    labels:
      - "type:documentation"
  - title: "🛠 Configuration"
    labels:
      - "type:config"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
template: |
  ## Changes
  $CHANGES
