#!/bin/bash

# check commit message
# - not empty
function checkEmpty() {
  local VALUE=$1
  local SPLIT_VALUE=($(echo "$VALUE" | tr "] " "\n"))

  if [[ "${SPLIT_VALUE[0]:0:1}" != "[" || -z "${SPLIT_VALUE[0]:1}" ]]
  then
    echo "Prefix is empty"
    echo "value = $VALUE"
    exit 1
  fi

  if [[ -z "${SPLIT_VALUE[1]}" ]]
  then
    echo "Commit message is empty"
    echo "value = $VALUE"
    exit 1
  fi
}

# - max length
function checkMaxLength() {
  local MAX_LENGTH="$1"
  local VALUE="$2"

  if [[ "${#VALUE}" -gt "$MAX_LENGTH" ]]
  then
    echo "Commit message is longer than the maximum length"
    echo "value = $VALUE"
    exit 1
  fi
}

# variables
MESSAGE=$(cat "$1")

# checking
checkEmpty "$MESSAGE"
checkMaxLength 72 "$MESSAGE"
