#!/usr/local/bin/bash

# check commit message
# - validate task number
function validateTaskNumber() {
  local VALUE=$1

  local REGEXP="^\[[A-Z]+-[0-9]+\]$"
  if [[ ! "$VALUE" =~ $REGEXP ]]
  then
    echo "The issue number is not specified correctly"
    echo "value = $VALUE"
    exit 1
  fi
}

# - not empty
function checkEmptyBody() {
  local VALUE=$1

  if [[ -z "$VALUE" ]]
  then
    echo "Commit message is empty"
    echo "value = $VALUE"
    exit 1
  fi
}

# - max length
function checkMaxLength() {
  local MAX_LENGTH="$1"
  local VALUE="$2"

  if [[ "${#VALUE}" -gt "$MAX_LENGTH" ]]
  then
    echo "Commit message is longer than the maximum length"
    echo "value = $VALUE"
    exit 1
  fi
}

# variables
MESSAGE="$1"
echo "$MESSAGE"
exit 1

# checking
# validateTaskNumber "${MESSAGE_CHUNKS[0]}"
# checkEmptyBody "$TAIL"
# checkMaxLength 72 "$MESSAGE"
