name: "Auto merge of approved pull requests with passed checks"

on:
  pull_request:
    types:
      - labeled
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    if: ${{ github.event.label.name == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Automerge PR"
        uses: "pascalgn/automerge-action@v0.14.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: "squash"
          MERGE_LABELS: "approved,!work in progress"
          MERGE_REMOVE_LABELS: "approved"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "10000"
          UPDATE_LABELS: "disable"
          MERGE_DELETE_BRANCH: true

      - name: "Run another workflows"
        uses: "peter-evans/repository-dispatch@v1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: auto_merge_pr
          repository: ${{ github.repository }}
