name: "Auto merge of approved pull requests with passed checks"

on:
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: "Automerge PR"
        uses: "KeisukeYamashita/auto-pull-request-merge@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          labels: "approved"
          strategy: "aquash"
