name: "Auto assign assignees or reviewers"
on:
  pull_request:
    type: [opened, ready_for_review]

jobs:
  add-reviews:
    name: "Auto assignment of a assignee"
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: ".github/assignee.config.yml"
