name: Create release drafter

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [auto_merge_pr]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
