name: Create release drafter

on:
  push:
    - master
  pull_request:
    types:
      - closed

jobs:
  update-release-draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
