name: Create release drafter

on:
  push:
    branches:
      - master
  repository_dispatch:

jobs:
  update-release-draft:
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
