name: Create release drafter

on:
  push:
    branches:
      - master
  workflow_run:
    workflows:
      - "Auto merge of approved pull requests with passed checks"
    types:
      - completed

jobs:
  update-release-draft:
    if: ${{ github.event.push.branch == 'master' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
