name: Echo

on:
  push:
    branches:
      - "**"

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Echo repository"
        run: |
          ls -la .

      - name: "Echo tags"
        run: |
          ls -la ./.git/refs/tags
