name: Verify labels in PR

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  label-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed: approved,
            type:feature,
            type:style,
            type:test,
            type:bugfix,
            type:docs,
            type:refactor,
            type:perf,
            type:config,
            type:build,
            type:ci
