name: Verify labels in PR

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  label-verify:
    runs-on: ubuntu-latest
    steps:
      - uses: zwaldowski/match-label-action@v2
        with:
          allowed_multiple: approved,
            type:feature,
            type:style,
            type:test,
            type:bugfix,
            type:docs,
            type:refactor,
            type:perf,
            type:config,
            type:build,
            type:ci

  run-another-workflows:
    needs: label-verify
    runs-on: ubuntu-latest
    steps:
      - name: "Run another workflows"
        uses: "peter-evans/repository-dispatch@v1"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: auto_merge_pr
          repository: ${{ github.repository }}
