name: Build and Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set version in package.json"
        run: |
          git config --global user.email "bot@github.actions"
          git config --global user.name "github actions bot"
          sed -i 's/"version":.*/"version": "0.0.1",/' package.json
          git add package.json
          git commit --amend --no-edit
          git push --force
