name: Build and Deploy

on:
  push:
    branches:
      - "**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Set version in package.json"
        run: |
          sed -i 's/"version":.*/"version": "0.0.1",/' package.json
          git config --global user.email "bot@github.actions"
          git config --global user.name "github actions bot"
          git add package.json
          cat package.json
          git commit --amend --no-edit
          git push
